name: steam-games-web-scraping-eda
channels:
  - conda-forge
dependencies:
  - python==3.10.4
  - pip==21.2.4
  - pip:
    - jupyter==1.0.0
    - nb_black==1.0.7
    - papermill==2.3.3
    - numpy==1.23.0
    - pandas==1.4.3
    - matplotlib==3.5.2
    - seaborn==0.11.2
    - selenium==4.3.0
    - lxml==4.9.1
    - beautifulsoup4==4.11.1
    - fake-useragent==0.1.11
    - sqlalchemy==1.4.39
    - mysql-connector-python==8.0.29
    - pymysql==1.0.2
    - prefect==1.2.2
    - fastparquet==0.8.1
    - pyarrow==8.0.0
    - azure-storage-blob==12.12.0
    - boto3
    - s3fs
